---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: democratic-csi
spec:
  interval: 1h0m0s
  url: https://democratic-csi.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi-system
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: '0.14.x'
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: democratic-csi-system
      interval: 1m
  values:
    speaker:
      tolerateMaster: false

